# Generated by Django 4.1.4 on 2023-01-02 23:30

from django.db import migrations, models
import django.template.context_processors


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=django.template.context_processors.media)),
            ],
        ),
    ]
