# Generated by Django 4.1.4 on 2023-01-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineplants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='image',
            field=models.ImageField(upload_to='profile'),
        ),
    ]
