# Generated by Django 4.1.4 on 2023-01-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sellerdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellername', models.CharField(blank=True, max_length=100, null=True)),
                ('sellerpassword', models.CharField(blank=True, max_length=100, null=True)),
                ('selleraddress', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
