# Generated by Django 4.1.4 on 2023-01-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_cdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='plantdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(blank=True, max_length=100, null=True)),
                ('pdetail', models.CharField(blank=True, max_length=100, null=True)),
                ('pprice', models.CharField(blank=True, max_length=100, null=True)),
                ('pimage', models.ImageField(upload_to='puploads')),
            ],
        ),
    ]
