# Generated by Django 4.1.4 on 2023-01-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_plantdetail_pimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantdetail',
            name='sellercode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plantdetail',
            name='pimage',
            field=models.ImageField(upload_to='profile'),
        ),
    ]
